version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: carrot
      POSTGRES_DB: ticket_service
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Add this line to mount init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      DB_USER: postgres
      DB_PASSWORD: carrot
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ticket_service
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
